{% set version = '0.5-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-condvis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/condvis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/condvis/condvis_{{ version }}.tar.gz
  sha256: 72ed0618a79d5b3ddd1ff2b95b2ce8bbdd7ebda4443510cc6606e50a94c3fdd9

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('condvis')"           # [not win]
    - "\"%R%\" -e \"library('condvis')\""  # [win]

about:
  home: https://github.com/markajoc/condvis/
  doc_url: http://markajoc.github.io/condvis/
  license: GPL-2.0-or-later
  summary: Exploring fitted models by interactively taking 2-D and 3-D sections in data space.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: condvis
# Type: Package
# Title: Conditional Visualization for Statistical Models
# Version: 0.5-1
# Date: 2018-09-13
# Authors@R: c( person("Mark", "O'Connell", email = "mark_ajoc@yahoo.ie", role = c("aut", "cre")), person("Catherine", "Hurley", role = "aut"), person("Katarina", "Domijan", role = "aut"), person("Achim", "Zeileis", role = "ctb", comment = "spineplot, see copied.R"), person("R Core Team", role = "ctb", comment = "barplot, see copied.R") )
# Depends: R (>= 2.1.0)
# Imports: graphics, grDevices, stats, utils, MASS
# Suggests: RColorBrewer, shiny, scagnostics, cluster, hdrcde, gplots, TSP, DendSer, testthat
# Description: Exploring fitted models by interactively taking 2-D and 3-D sections in data space.
# License: GPL (>= 2)
# LazyData: false
# BugReports: https://github.com/markajoc/condvis/issues
# URL: http://markajoc.github.io/condvis/
# RoxygenNote: 5.0.1.9000
# Packaged: 2018-09-12 23:06:07 UTC; mark
# Author: Mark O'Connell [aut, cre], Catherine Hurley [aut], Katarina Domijan [aut], Achim Zeileis [ctb] (spineplot, see copied.R), R Core Team [ctb] (barplot, see copied.R)
# Maintainer: Mark O'Connell <mark_ajoc@yahoo.ie>
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2018-09-13 04:50:03 UTC
